### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Spaxe** [Virtual-Technology-Laboratory/ProceduralTerrain#1]
This script looks exactly like what I can use in a project, and I'm playing with it today.

Could you add a LICENSE file to specify what kind, in particular commercial use, is permissible?

MIT would be brilliant.

**Comment by rogerlew** [comment]
Hi Xavier,

You are free to use it under the 3 clause BSD license.
Roger

**Comment by Spaxe** [comment]
Thanks Roger!
